import React from 'react';
import { Components, registerComponent } from 'meteor/vulcan:core';

const BackofficeIndex = () => (
  <div>
    <p>Welcome to Vulcan autogenerated backoffice</p>
    <div>
      <Components.AccountsLoginForm />
    </div>
  </div>
);
registerComponent({ name: 'VulcanBackofficeIndex', component: BackofficeIndex, hocs: [] });

export default BackofficeIndex;
