import React from 'react';
import { registerComponent } from 'meteor/vulcan:core';

const BackofficeIndex = () => <div>Welcome to Vulcan autogenerated backoffice</div>;
registerComponent({ name: 'VulcanBackofficeIndex', component: BackofficeIndex, hocs: [] });

export default BackofficeIndex;
