language: node_js
node_js:
  - "0.10"
before_install:
  - curl https://install.meteor.com | /bin/sh

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  # Add testing package since it's not currently enabled in Telescope
  - printf "sanjo:jasmine@0.11.0" >> .meteor/packages

script:
  - JASMINE_BROWSER=Firefox meteor --test