import Users from 'meteor/vulcan:users';
import { setupBackoffice } from 'meteor/vulcan:backoffice';
import _merge from 'lodash/merge';
import enhanceUsersFormWithPassword from '../components/enhanceUsersForm';

const defaultOptions = {
  list: {
    basicColumns: [
      //"_id",
      'createdAt',
      'username',
      'email',
      'isAdmin',
      //"groups"
    ],
    accessGroups: ['admins'],
    accessRedirect: '/',
    headerTextToken: 'usersManager.header.list',
  },
  details: {
    fields: ['_id', 'createdAt', 'username', 'email', 'isAdmin', 'groups'],
    accessGroups: ['admins'],
    accessRedirect: '/',
  },
  form: {
    newFields: ['username', 'email', '_password', 'groups', 'isAdmin'],
    editFields: ['_id', 'createdAt', 'username', 'email', '_password', 'groups', 'isAdmin'],
    accessGroups: ['admins'],
    accessRedirect: '/',
    headerTextToken: 'usersManager.header',
  },
  menuItem: {
    labelToken: 'usersManager.collectionName',
  },
};
const enhanceBackofficeWithUsers = (options = {}) => {
  const mergedOptions = _merge({}, defaultOptions, options);
  setupBackoffice([Users], {}, { Users: mergedOptions });
  // now we can enhance the autogenerated UsersForm to add the password field
  enhanceUsersFormWithPassword(options.usersFormComponentName);
};

export default enhanceBackofficeWithUsers;
